# For test purposes only
version: "3.9"
services:
  postgresdb:
    image: postgres:15
    environment:
      POSTGRES_USER: lakefs
      POSTGRES_PASSWORD: lakefs
      POSTGRES_DB: lakefs
    volumes:
      - postgres-db-volume2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "lakefs"]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"

  lakefs:
    image: treeverse/lakefs:0.106.2
    command: run --quickstart
    ports:
      - "8001:8001"
    environment:
      - LAKEFS_BLOCKSTORE_TYPE=local
      - LAKEFS_DATABASE_TYPE=postgres
      - LAKEFS_DATABASE_POSTGRES_CONNECTION_STRING=postgresql://lakefs:lakefs@postgresdb:5432/lakefs?sslmode=disable
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=a123456
      - LAKEFS_LOGGING_LEVEL=INFO
      - LAKEFS_LOGGING_AUDIT_LOG_LEVEL=INFO
      - LAKEFS_LISTEN_ADDRESS=0.0.0.0:8001
      - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE=true
      - LAKEFS_BLOCKSTORE_S3_DISCOVER_BUCKET_REGION=false
    depends_on:
      postgresdb:
        condition: service_healthy


volumes:
  postgres-db-volume2:

